### ISSUE TITLE
没有测试的数据

### ISSUE THREAD

**Issue by YiZhiWN** [ruiyong-lee/weapp-vue-eggjs-shop-demo#13]

**Comment by YiZhiWN** [comment]
楼主有测试的数据吗

**Comment by ruiyong-lee** [comment]
目前本地是可以完整跑起来的，初始化一个管理员就可以开始建数据。
如果非要测试数据用我这个，但是小程序appid你要用自己的才能打开。
[weapp-vue-eggjs-shop-demo.zip](https://github.com/ruiyong-lee/weapp-vue-eggjs-shop-demo/files/3481170/weapp-vue-eggjs-shop-demo.zip)

**Comment by YiZhiWN** [comment]
好的，谢谢
