### ISSUE TITLE
如何同步数据库

### ISSUE THREAD

**Issue by zuumau** [ruiyong-lee/weapp-vue-eggjs-shop-demo#4]
如果我修改了 schema 后， 如何同步到数据库呢
我再次运行  npm run db:up

会提示 
No migrations were executed, database schema was already up to date.
```
    "db:init": "npx sequelize migration:generate --name",
    "db:up": "npx sequelize db:migrate",
    "db:down": "npx sequelize db:migrate:undo",
    "db:down-all": "npx sequelize db:migrate:undo:all"
```

**Comment by zuumau** [comment]
我新建了个新项目  运行了   npm run db:init
然后又了  database 的文件夹  
但是里面没有  db.js   和 config.json  这两个文件
我该如何做

**Comment by ruiyong-lee** [comment]
执行npm run db:init 只是在database -> migrations 目录下生成一个新的 migration 文件，怎么会把原来项目里面的 config.json 和 db.js 都删除了？db.js这是我自己写的。我自己是这么认为的，schema那边修改了，执行npm run db:init，在里面写代码执行变更数据库，具体写法可参考最初的20180917093817-init.js文件，文档接口看：[http://docs.sequelizejs.com/class/lib/query-interface.js~QueryInterface.html](url)，然后执行npm run db:up。Migrations就是用来帮我们管理数据结构的变更

**Comment by zuumau** [comment]
按照你的方法做了，就是用 demo 的代码  
先修改了   schema  文件，增加了一个字段
然后   npm run db:init     执行了
再执行npm run db:up  的时候报错了
错误是
```
Loaded configuration file "database\config.json".
Using environment "development".
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules\sequelize\lib\sequelize.js:242:13
== 20190402063610-unnamed-migration: migrating =======

ERROR: Migration 20190402063610-unnamed-migration.js (or wrapper) didn't return a promise

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app-server@1.0.0 db:up: `npx sequelize db:migrate`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the app-server@1.0.0 db:up script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-04-02T06_39_43_410Z-debug.log
```

**Comment by ruiyong-lee** [comment]
那有可能是写错了，是否方便贴一下你的代码？

**Comment by zuumau** [comment]
我下载 demo 之后， 已经  up  过一次，  表全都生成了
 然后我改了     schema/admin.js
```
    lastModifierName: {
      type: STRING(176),    // 之前是  76  ，我改成了 176 , 
      allowNull: false,
    },
```  
 然后再运行 init + up  就报上面的错误

**Comment by ruiyong-lee** [comment]
执行 npm run db:init 新生成的 20190402063610-unnamed-migration.js，我的意思是schema/admin.js改了，然后还要在20190402063610-unnamed-migration.js里面写代码变更数据库，具体参照我写的那个和刚才提供的文档。如果你只是想同步模型到数据库，只要在启动的时候(app.js)执行：sequelize.sync() 就可以了，这样schema/admin.js修改就会同步到数据库，但是不推荐这么操作，官方原话：
> 我们可以直接通过 mysql 命令将表直接建好，但是这并不是一个对多人协作非常友好的开发模式。在项目的演进过程中，每一个迭代都有可能对数据库数据结构做变更，怎样跟踪每一个迭代的数据变更，并在不同的环境（开发、测试、CI）和迭代切换中，快速变更数据结构呢？这时候我们就需要 Migrations 来帮我们管理数据结构的变更了。

**Comment by zuumau** [comment]
只要在启动的时候(app.js)执行：sequelize.sync() 就可以了
这个怎么执行， 是命令吗， 还是把代码加到 app.js

**Comment by ruiyong-lee** [comment]
代码写到app.js里面，就像你发的这个文档的示例一样。[sequelize-docs-Zh-CN](https://github.com/demopark/sequelize-docs-Zh-CN)

**Comment by klren0312** [comment]
> “只要在启动的时候(app.js)执行：sequelize.sync() 就可以了”
> 
> 这个怎么执行， 是命令吗， 还是把代码加到 app.js

'use strict';

module.exports = app => {
  if (app.config.env === 'local') {
    app.beforeStart(async () => {
      // await app.model.sync({ force: true })
    })
  }
}

**Comment by ruiyong-lee** [comment]
#12
